name: Julien Lerouge
markdown: kramdown
safe: true
lsi: false
highlighter: rouge
url: http://julien.lerouge.me
paginate: 5
paginate_path: "blog/page:num"
author:
    pseudo: jlerouge
    display_name: Julien Lerouge
    job: R&D engineer @ <a href="http://www.a2ia.com">Mitek Systems Paris</a>
    activity: <ul class="no-bullets"><li>Machine learning</li><li>Image processing</li><li>Document analysis</li><li>Text recognition</li></ul>
    github: jlerouge
    twitter: julien_lerouge
    linkedin: julien-lerouge
    gravatar: 8abcd6b65764dea142df693e8a2c9b0e
    scholar: qmL0h5cAAAAJ
    orcid: 0000-0003-0363-9304
    researchgate: Julien_Lerouge2

coauthors:
    jle:
        name: J. Lerouge
        url: http://julien.lerouge.me
        email: julien.lerouge@a2ia.com
    jl:
        name: J. Lerouge
        url: http://julien.lerouge.me
        email: julien.lerouge@litislab.fr
    cc:
        name: C. Chatelain
        url: http://pagesperso.litislab.fr/cchatelain/
        email: clement.chatelain@insa-rouen.fr
    rh:
        name: R. Hérault
        url: http://pagesperso.litislab.fr/rherault/
        email: romain.herault@insa-rouen.fr
    rm:
        name: R. Modzelewski
        url: https://www.linkedin.com/in/romain-modzelewski-a500426/
        email: romain.modzelewski@chb.unicancer.fr
    fj:
        name: F. Jardin
        url: http://www.becquerel.fr/people/fabrice-jardin/
        email: hematologie@chb.unicancer.fr
    sa:
        name: S. Adam
        url: http://pagesperso.litislab.fr/sebadam/
        email: sebastien.adam@univ-rouen.fr
    ph:
        name: P. Héroux
        url: http://pierre.heroux.free.fr
        email: pierre.heroux@univ-rouen.fr
    mh:
        name: M. Hammami
        url: https://www.linkedin.com/in/maroua-hammami-kolbl/
        email: hammamimaroua@gmail.com
    pt:
        name: P. Tranouez
        url: http://pagesperso.litislab.fr/ptranouez/
        email: pierrick.tranouez@univ-rouen.fr
    sn:
        name: S. Nicolas
        url: https://scholar.google.fr/citations?user=OT776bsAAAAJ&hl=fr
        email: stephane.nicolas@univ-rouen.fr
    tp:
        name: T. Paquet
        url: http://pagesperso.litislab.fr/tpaquet/
        email: thierry.paquet@univ-rouen.fr
    plb:
        name: P. Le Bodic
        url: https://scholar.google.fr/citations?user=wQcDC-YAAAAJ
        email: lebodic@gatech.edu
    za:
        name: Z. Abu-Aisheh
        url: https://www.researchgate.net/profile/Zeina_Abu-Aisheh
        email: zeina.abu-aisheh@univ-tours.fr
    rr:
        name: R. Raveaux
        url: http://romain.raveaux.free.fr/
        email: romain.raveaux@univ-tours.fr
    jk:
        name: J. Kraut
    mm:
        name: M. Mehri
        url: https://l3i.univ-larochelle.fr/Mehri-Maroua-ATER
        email: maroua.mehri@univ-lr.fr
    pg:
        name: P. Gomez-Kramer
        url: https://l3i.univ-larochelle.fr/Gomez-Kramer-Petra-MCF
        email: petra.gomez@univ-lr.fr
    rmu:
        name: R. Mullot
        url: https://l3i.univ-larochelle.fr/Mullot-Remy-Pr
        email: remy.mullot@univ-lr.fr
    mc:
        name: M. Coustaty
        url: https://l3i.univ-larochelle.fr/Coustaty-Mickael-MCF
        email: mickael.coustaty@univ-lr.fr
    ws:
        name: W. Swaileh
        url: http://pagesperso.litislab.fr/wswaileh/
        email: wassim.swaileh2@univ-rouen.fr

affiliations:
    litis-insa: Normandie Université, LITIS EA 4108, INSA Rouen, 76800 Saint-Étienne-du-Rouvray, France
    litis-univ-rouen: Normandie Université, LITIS EA 4108, University of Rouen, 76801, Saint-Etienne du Rouvray, France
    latis: LATIS Laboratory, Sousse University, National Engineering School of Sousse, 4023, Sousse Erriadh, Tunisia
    nuclear-becquerel: Department of Nuclear Medicine, Henri Becquerel Cancer Center and Rouen University Hospital, 76000 Rouen, France
    hematology-becquerel: Department of Clinical Hematology and INSERM U918 Unit, Henri Becquerel Cancer Center, 76000 Rouen, France
    isye-gatech: H. Milton Stewart School of Industrial and Systems Engineering, Georgia Institute of Technology, 765 Ferst Drive NW, Atlanta, 30332, USA
    l3i: L3I Laboratory, University of La Rochelle, av M. Crépeau, 17042 La Rochelle Cedex 1, France
    li-tours: LI Tours, Avenue Jean Portalis, Tours, France
