name: Julien Lerouge
markdown: redcarpet
safe: true
lsi: false
pygments: true
url: http://julien.lerouge.me
paginate: 5
paginate_path: "news/page:num"
author:
    pseudo: jlerouge
    display_name: Julien Lerouge
    activity: R&D engineer @ <a href="http://www.litislab.fr">LITIS</a> laboratory
    slogan: C++ and Python enthusiast
    github: jlerouge
    twitter: jujurackham
    linkedin: 176494391
    googleplus: JulienLerouge
    gravatar: b3a8c2b99efbf289c48ddb39e24a1199
