name: Julien Lerouge
markdown: redcarpet
safe: true
lsi: false
pygments: true
url: http://julien.lerouge.me
paginate: 5
paginate_path: "blog/page:num"
author:
    pseudo: jlerouge
    display_name: Julien Lerouge
    github: jlerouge
    twitter: jujurackham
    linkedin: 176494391
    googleplus: JulienLerouge
    gravatar: b3a8c2b99efbf289c48ddb39e24a1199
