name: Julien Lerouge
markdown: redcarpet
pygments: true
url: http://julien.lerouge.me

author:
    pseudo: jlerouge
    display_name: Julien Lerouge
    github: jlerouge
    twitter: jujurackham
    linkedin: 176494391
    googleplus: JulienLerouge
    gravatar: b3a8c2b99efbf289c48ddb39e24a1199